name: release-please

on:
    push:
        branches:
            - master
    workflow_dispatch:
        inputs:
            tag:
                description: release git tag to npm manually
                required: false
                type: string
            release_next:
                description: release pre-release version
                required: true
                type: boolean

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              if: ${{ !github.event.inputs.tag }}
              id: release
              with:
                  manifest-file: .github/.release-manifest.json
                  config-file: ${{ github.event.inputs.release_next == 'true' && '.github/.release-config.next.json' || '.github/.release-config.json' }}
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

            - uses: actions/checkout@v5
              if: ${{ steps.release.outputs.release_created || github.event.inputs.tag }}
              with:
                  ref: ${{ github.event.inputs.tag || 'master' }}

            - uses: actions/setup-node@v4
              if: ${{ steps.release.outputs.release_created || github.event.inputs.tag}}
              with:
                  cache: npm
                  node-version: 24
                  registry-url: "https://registry.npmjs.org"

            - if: ${{ steps.release.outputs.release_created || github.event.inputs.tag }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npm install
                  node --run build
                  npm publish \
                    --provenance \
                    --access public \
                    --tag ${{ github.event.inputs.release_next == 'true' && 'next' || 'latest' }}
